### ISSUE TITLE
Sort namespaces in treeview

### ISSUE THREAD

**Issue by mvriel** [phpDocumentor/template.clean#15]
@LukeCarrier (twitter handle) posted this feature request: https://twitter.com/LukeCarrier/status/383345980378083328

**Comment by toxalot** [comment]
I just upgraded to 2.4 via PEAR. The namespaces in left sidebar and top of the default page are NOT sorted alphabetically by namespace name. The order depends on the order in which the files were parsed.

@mvriel Can you take another look at this?
