### ISSUE TITLE
404 Error not found when Clicking on Source link

### ISSUE THREAD

**Issue by shollingsworth** [phpDocumentor/template.clean#42]
When the template is compiled.

source: MyFile1.php

created:
files/MyFile1.html
files/MyFile1.php.txt

source:
app/MyFile2.php

created:
files/MyFile2.html
files/app%2FMyFile2.php.txt

If the source is in a subdirectory I get a 404 error. If the source is in the first path, the link works fine.

**Comment by mvriel** [comment]
Thanks for reporting this; perhaps some encoding triggers this bug.

**Comment by mvriel** [comment]
This issue should be resolved in PR #43 (thanks @siad007) and will be included in the next release
